version: '3'
services:

  postgres:
    image: postgres:11.6-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=exampledev
    - POSTGRES_USER=exampledev
    - POSTGRES_PASSWORD=exampledev
    - MAX_CONNECTIONS=300